version: '3.2'
services:
###############################################################################
# rails app
###############################################################################
  rails-app:
    build: .
    depends_on:
      - rails-db
    env_file:
      - .docker.env
    ports:
      - 3000:3000
    stdin_open: true
    command: rails loumaris:start
    tty: true
    volumes:
      - ./:/app

###############################################################################
# rails postgreSQL db
###############################################################################
  rails-db:
    image: postgres:14-alpine
    env_file:
      - .docker.env
    volumes:
      - rails-pgdata:/var/lib/postgresql/data

###############################################################################
# rails volumes
###############################################################################
volumes:
  rails-pgdata:
    driver: local
